### ISSUE TITLE
[Feature Request] Add api method for render the dialog by roll a item on Character Sheet

### ISSUE THREAD

**Issue by p4535992** [jessev14/Multiattack-5e#15]
Can you add a method in the api to open the dialog from the actor for an integration with the item macro module ?
I would like to be able to open the dialog of multiattacck by clicking on an item in the character sheet

So retrieve the weapons with something like this:

```
function retrieveAllWeaponsAndSpellFromActor(actor) {
  const physicalItems = ["weapon", "spell"];
  let weapons = [];
  for(let im of actor.items.contents) {
    // OPTIONAL ADD CHECK FOR SPELL SLOTS AND AMMUNITION
    if (im && physicalItems.includes(im.type)) {
      weapons.push(im);
    }
  };
  return weapons;
}
```

and call the module for render the dialog with something like this:

`game.MA5e.midiMA5eDialog(actor)`

**Comment by jessev14** [comment]
So the documentation needs some work, but there is a function to just make the roll that you would normally get from the dialog window:
`game.modules.get('multiattack-5e').api.multiattack`
which takes an object argument in the form of:
```js
{
    actor,
    itemNameArray = [], itemIDarray = [], chatMessage = true, messageData, primeRoll,
    isAttackRoll = true, isExtraAttack = false,
    rollMode = 'publicroll', sitBonus, vantage = 'normal', isCritical = false
}
```

So what I think might work without any additions to the API is to create an item macro that collects the items you want to include in the roll and do something like:

```js
const itemsToRoll = []; // Array of item names on actor.

const ma5eData = {
    actor, // I think item macros define 'actor' as the item owner automatically.
    itemNameArray: itemsToRoll,
};

let rollMode;
// This dialog lets the user decide if they are doing an attack or damage roll.
// If you're using MIDI (compatibility not confirmed), you can skip this dialog and just run game.modules.get('multiattack-5e').api.multiattack(ma5eData);
new Dialog({
    title: 'Roll Mode',
    buttons: {
        attack: {
            label: 'Attack',
            callback: () => rollMode = 'attack'
        },
        damage: {
            label: 'Damage',
            callback: () => rollMode = 'damage'
        }
    },
    close: () => {
        if (!rollMode) return;

        ma5eData.rollMode = rollMode;
        game.modules.get('multiattack-5e').api.multiattack(ma5eData);
    }
}).render(true);

```

This is admittedly probably not what you're looking for, since I imagine you would want the user to be able to specify how many times each item is rolled each time the item macro is called. If this is the case, let me know and I can adjust the API to include a method for opening the multiattack tool dialog with specified items.

**Comment by p4535992** [comment]
It should be enough for my use case. If i really need it the extra step i'll let you know . Ty for your time,
